### ISSUE TITLE
JSON Decoder Error while testing the Sportradar Soccer example

### ISSUE THREAD

**Issue by qasimali000** [johnwmillr/SportradarAPIs#17]
Hi,

I was trying to reproduce the provided example on github but I'm getting JSON Decoder error. I tried to backtrack the issue and it seems like its not passing the API key correctly. 

Can you please help me fixing this.

Following is the error I'm getting:

soccer-t3/intl/en/tournaments
http://api.sportradar.us/soccer-t3/intl/en/tournaments.json
Traceback (most recent call last):
  File "/Users/qasimali/PycharmProjects/sportradar/main.py", line 23, in <module>
    tournaments = sr.get_tournaments().json()
  File "/Users/qasimali/PycharmProjects/sportradar/venv/lib/python3.9/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by eloco17** [comment]
I am also getting the same exact error
